// Generated by CoffeeScript 1.3.3
(function() {

  requirejs.config({
    paths: {
      lib: '../lib'
    },
    shim: {
      'zepto': {
        exports: function() {
          return this.Zepto;
        }
      },
      'showdown': {
        exports: 'Showdown'
      },
      'reveal': {
        exports: 'Reveal'
      },
      'lib/highlight': {
        exports: 'hljs'
      },
      'lib/classList': {
        exports: 'classList'
      }
    }
  });

  define(function(require, exports, module) {
    var Preso, Reveal, hljs, p;
    Preso = require("preso");
    p = new Preso();
    Reveal = require("reveal");
    Reveal.initialize({
      controls: true,
      progress: true,
      history: true,
      keyboard: true,
      loop: false,
      mouseWheel: true,
      rollingLinks: false,
      theme: 'default',
      transition: 'default'
    });
    hljs = require('lib/highlight');
    return hljs.initHighlightingOnLoad();
  });

}).call(this);
